export const siteConfig = {
  name: "Jayesh Vegda | Full Stack Developer",
  authorName: "Jayesh Vegda",
  username: "jayeshvegda",
  description:
    "Full Stack Developer with expertise in modern web technologies including React, Node.js, Python, and cloud platforms. Proven track record of building scalable applications through comprehensive training and hands-on project experience. Strong problem-solving skills with 350+ coding challenges solved.",
  url: "https://jayeshvegda.dev",
  links: {
    twitter: "https://leetcode.com/jayeshvegda",
    github: "https://github.com/jayeshvegda",
    linkedin: "https://www.linkedin.com/in/jayeshvegda/",
  },
  ogImage: "/profile-img.jpg",
  iconIco: "/logo.png",
  logoIcon: "/logo.png",
  keywords: [
    "Jayesh Vegda",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "React Developer",
    "Node.js Developer",
    "Python Developer",
    "Full Stack Web Development",
    "MERN Stack",
    "Software Developer",
    "Web Developer",
    "Frontend Developer",
    "Backend Developer",
    "Next.js Developer",
    "React.js Developer",
    "JavaScript Developer",
    "TypeScript Developer",
    "Problem Solver",
    "Competitive Programming",
  ],
};
